spring:
  application:
    name: techbip
  datasource:
    url: jdbc:postgresql://localhost:5432/techbip
    username: 
    password: 
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        time_zone: UTC
    hibernate:
      ddl-auto: create-drop
app:
  jwtSecret: KerimJWTSecretKey
  jwtExpiration: 64000000
server:
  error:
    include-message: always
    include-stacktrace: never
  port: 8081

